### PR TITLE
[Feature] Add `Student` class

### LINKED ISSUE #2: [Feature] Add Student class
### Describe the Feature

The feature I'm requesting is that a `Student` class be added. This class will **extend the Person class** and contain support for **simple tracking of test scores**.

### Importance of Feature

Kinda important?

### PR DESCRIPTION
**Pull request by ErnWong**
# Overview

Add `Student` class is added.
Basic tracking of test scores is implemented.
closes #2

## The Issue

Some stranger on the internet told me to implement #2

## The Solution

Implement #2

## The Closing Comments

#2 is implemented

### CODE REVIEW

**Review by ErnWong — COMMENTED** [review]
​

**Review by Matteas-Eden — CHANGES_REQUESTED** [review]
Please pull down the latest changes from `master` and rebase your branch on top.

**Comment by ErnWong** [comment]
> Please pull down the latest changes from `master` and rebase your branch on top.

Rebased ✅

**Comment by ErnWong** [comment]
FYI: build failed in forked repo: https://github.com/ErnWong/yet-another-maven-repo/runs/4057226352?check_suite_focus=true

**Comment by Matteas-Eden** [comment]
> FYI: build failed in forked repo: https://github.com/ErnWong/yet-another-maven-repo/runs/4057226352?check_suite_focus=true

I think the latest changes on `master` solves this, so try rebasing again? What's more worrying to me is that the SonarCloud checks aren't running in this PR.

**Comment by ErnWong** [comment]
FYI: Build still fails in my fork because I got the import wrong, but why is it building successfully in this PR?

See: https://github.com/ErnWong/yet-another-maven-repo/runs/4057811889?check_suite_focus=true
versus: https://github.com/Matteas-Eden/yet-another-maven-repo/pull/3/checks

**Comment by Matteas-Eden** [comment]
> FYI: Build still fails in my fork because I got the import wrong, but why is it building successfully in this PR?
> 
> See: https://github.com/ErnWong/yet-another-maven-repo/runs/4057811889?check_suite_focus=true versus: https://github.com/Matteas-Eden/yet-another-maven-repo/pull/3/checks

I have no idea. Previously I thought it was due to an incorrectly placed `continue-on-error: true`, but it seems as though that wasn't the problem. Further to that, I think there may be an issue with running SonarCloud on PRs from forked repos: https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request

**Comment by Matteas-Eden** [comment]
@ErnWong Could I ask you to rebase off of master, one more time?

**Comment by ErnWong** [comment]
> @ErnWong Could I ask you to rebase off of master, one more time?

Rebased ✅

**Review by Matteas-Eden — COMMENTED** [review]
Okay, I've restructured the workflows. Try rebasing again ~~hopefully for the last time~~.

**Review by Matteas-Eden — CHANGES_REQUESTED** [review]
Can I get a getter for the `testScore` field, and some relevant tests?

**Comment by Matteas-Eden** [comment]
Another rebase, please.

**Comment by Matteas-Eden** [comment]
@ErnWong I'll take one `git rebase origin master` to go, please.

**Comment by ErnWong** [comment]
> @ErnWong I'll take one `git rebase origin master` to go, please.

🍞

**Comment by Matteas-Eden** [comment]
Sorry, what about a rebase with some :fries: ?

**Comment by ErnWong** [comment]
> Sorry, what about a rebase with some 🍟 ?

🥡

**Comment by ErnWong** [comment]
> > Sorry, what about a rebase with some 🍟 ?
> 
> 🥡

🦠

**Comment by ErnWong** [comment]
> > > Sorry, what about a rebase with some 🍟 ?
> > 
> > 
> > 🥡
> 
> 🦠

💩

**Review by Matteas-Eden — APPROVED** [review]
Thanks for this PR, and thank you for continually rebasing it while I was testing out SonarCloud integration. Although the SonarCloud integration was a bust (https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request), this PR is good-to-go.

Thanks again @ErnWong.

**Pull request merged**
